#!/bin/bash

#
# For I2P to not be routed over Tor, we exempt
# the "i2p" user from the iptables REDIRECT rules.
#
# The problem with this though is that any compromise
# of the "i2p" user allows for an IP address leak.
#
# We cannot add the required iptables rules to
# /etc/iptables/iptables.rules as, during installation
# that will attempt to force the I2P installer over
# I2P which doesn't exist yet.
#
# This implementation sets the needed iptables rule to
# redirect all traffic from the "i2p" user to port
# 4444 (the default I2P http proxy) after I2P has been
# installed.
#
# A sudoers exception is added in /etc/sudoers.d/i2p to
# allow the user "user" to run this script and plug the
# firewall without root.
#
# This cannot be exploited as an attacker would just be
# able to re-apply the same rule over and over again.
#

iptables -A OUTPUT -t nat -p tcp -m owner --uid-owner "i2p" -j REDIRECT --to-ports 4444
